---
- hosts: redisservers

  vars:
    base_path: ../
    versions:
      - redis-2.8.24
      - redis-3.0.6
      - redis-3.2.11
      - redis-4.0.12
      - redis-5.0.3

  tasks:
  - name: copy redis file to remote server
    copy: src={{ base_path }}/software_package/{{ item }}.tar.gz dest={{ base_path }} owner=redis group=redis mode="u=rw,g=r,o=r"
    with_items: "{{ versions }}"

  - name: unarchive redis file
    shell: cd {{ base_path }};tar -zxvf {{ item }}.tar.gz
    with_items: "{{ versions }}"

  - name: make redis
    shell: cd {{ base_path }}/{{ item }}; make -j{{ ansible_processor_vcpus * 2 }}
    with_items: "{{ versions }}"